### ISSUE TITLE
Version in README is outdated

### ISSUE THREAD

**Issue by ciscam** [getdrunkonmovies-com/TS3AudioBot_docker#10]
`# docker run --rm -v $(pwd)/data:/data -it ancieque/ts3audiobot:0.11.0`
`Unable to find image 'ancieque/ts3audiobot:0.11.0' locally`
`docker: Error response from daemon: manifest for ancieque/ts3audiobot:0.11.0 not found: manifest unknown: manifest unknown.`
`See 'docker run --help'.`

**Comment by s4ke** [comment]
thanks. merged.
