### ISSUE TITLE
i am getting this

### ISSUE THREAD

**Issue by GhostingGodzilla** [getdrunkonmovies-com/TS3AudioBot_docker#14]
23:54:48.3248| INFO|Core| [============ TS3AudioBot started =============]
23:54:48.3579| INFO|Core| [ Date: Friday, 22 April 2022 23:54:48
23:54:48.3805| INFO|Core| [ Version: 0.12.0/master/768c1867
23:54:48.3805| INFO|Core| [ Build: Release
23:54:48.3805| INFO|Core| [ Platform:   (64bit)
23:54:48.3883| INFO|Core| [ Runtime: .NET Core (3.1.22) ServerGC:True GC:SustainedLowLatency
23:54:48.3883| INFO|Core| [ Opus: libopus 1.3.1 (x64)
23:54:48.3883| INFO|Core| [==============================================]
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
23:54:48.5666|FATAL|Core| Critical program failure!
23:54:48.5824| INFO|Core| TS3AudioBot shutting down.
23:54:48.5824| INFO|Core| WebServer is closing
23:54:48.5896| INFO|Core| Bye
Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.IO.IOException: The process cannot access the file '/app/data/ts3audiobot.db' because it is being used by another process.
   at LiteDB.IOExceptionExtensions.WaitIfLocked(IOException ex, Int32 timer)
   at LiteDB.FileHelper.TryExec(Action action, TimeSpan timeout)
   at LiteDB.StreamExtensions.TryLock(FileStream stream, Int64 position, Int64 length, TimeSpan timeout)
   at LiteDB.FileDiskService.Lock(LockState state, TimeSpan timeout)
   at LiteDB.LiteEngine..ctor(IDiskService disk, String password, Nullable`1 timeout, Int32 cacheSize, Logger log, Boolean utcDate)
   at LiteDB.LiteDatabase.<>c__DisplayClass11_0.<.ctor>b__0()
   at LiteDB.LazyLoad`1.get_Value()
   at LiteDB.LiteCollection`1.Find(Query query, Int32 skip, Int32 limit)+MoveNext()
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
   at LiteDB.LiteCollection`1.FindById(BsonValue id)
   at TS3AudioBot.DbStore.GetMetaData(String table) in C:\projects\ts3audiobot\TS3AudioBot\DbStore.cs:line 34
   at TS3AudioBot.Environment.Stats..ctor(ConfRoot conf, DbStore database, BotManager botManager, DedicatedTaskScheduler scheduler) in C:\projects\ts3audiobot\TS3AudioBot\Environment\Stats.cs:line 68
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at TS3AudioBot.Dependency.InjectorExtensions.TryCreate(IInjector injector, Type type, Object& obj) in C:\projects\ts3audiobot\TS3AudioBot\Dependency\InjectorExtensions.cs:line 69
   at TS3AudioBot.Dependency.DependencyBuilder.Build() in C:\projects\ts3audiobot\TS3AudioBot\Dependency\DependencyBuilder.cs:line 95
   at TS3AudioBot.Core.Run(ParameterData setup) in C:\projects\ts3audiobot\TS3AudioBot\Core.cs:line 71
   at TS3AudioBot.Setup.StartBot(ParameterData setup) in C:\projects\ts3audiobot\TS3AudioBot\Setup.cs:line 92
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by s4ke** [comment]
This looks like /app/data/ts3audiobot.db is in use by another process. Are you sure you only have one Docker container running?

Closing this as this is not related to the Docker image itself.
